btamplate/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from .views import render_pdf_view

app_name = 'btamplate'


urlpatterns = [
    path('', views.index, name='index'),
    path('createTemplate/', views.createTemplate, name='createTemplate'),
    path('signup/', views.signup, name='signup'),
    path("login/", views.login_request, name="login"),
    path('update/', views.update, name='update'),
    path('contact/', views.contact, name='contact'), 
    path('test/<object_id>/',render_pdf_view, name='test-view'),
    path('delete_template/<object_id>/',views.delete_template, name='delete_template'),
    path('update_template/<object_id>/',views.update_template, name='update_template'),
    path('email/<object_id>/', views.email, name='email'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from btamplate import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('btamplate/', include('btamplate.urls')),
    
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

btamplate/models.py
from django.db import models
from datetime import date


class Formi(models.Model):
    pro_date = models.CharField(max_length=20)
    name = models.CharField(max_length=30)
    role = models.CharField(max_length=30)
    logo = models.ImageField(upload_to='media/')
    summary = models.TextField()
    project = models.TextField()
    limitations = models.TextField()
    approach = models.TextField()
    benefits = models.TextField()
    opportunities = models.TextField()
    nobel = models.TextField()
    threat = models.TextField()
    financial = models.TextField()
    risk = models.TextField()
    def __str__(self):
        return self.pro_date

btamplate/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Formi
from django.forms import ModelForm

class updateTemplate(forms.ModelForm):
    class Meta:
        model = Formi
        fields = ['pro_date', 'name','role','logo','summary','project','limitations','approach','benefits',
        'opportunities','nobel','threat','financial','risk']
 

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        def save(self, commit=True):
            user = super(UserRegisterForm, self).save(commit=False)
            user.email = self.cleaned_data['email']
            if commit:
                user.save()
            return user
        help_texts = {
            'username': None,
            'password1': None,
            'password2': None,
        }
class createForm(forms.Form):
    class Meta:
        model = Formi
        fields = ['pro_date','name','role','logo','summary','project','limitations','approach','benefits',
        'opportunities','nobel','threat','financial','risk']

btamplate/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from .forms import UserRegisterForm
from .forms import createForm
from .forms import updateTemplate
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import login, authenticate 
from django.contrib.auth.forms import AuthenticationForm
from .models import Formi
from django.http import FileResponse
from django.shortcuts import render, get_object_or_404
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import EmailMultiAlternatives
from email.mime.image import MIMEImage
from django.contrib.auth.models import User



def signup(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            # messages.success(request, f'Hi {username}, your account was created successfully')
            return redirect('btamplate:login')
    else:
        form = UserRegisterForm()
    return render(request, 'btamplate/signup.html', {'form': form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("btamplate:createTemplate")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="btamplate/login.html", context={"login_form":form})



def createTemplate(request):
    if request.method == "POST":
            form = createForm(request.POST, request.FILES)
            if form.is_valid():
                pro_date = request.POST.get("pro_date","")
                name = request.POST.get("name", "")
                role = request.POST.get("role", "")
                logo = request.FILES.get("logo", "")
                summary = request.POST.get("summary", "")
                project = request.POST.get("project", "")
                limitations = request.POST.get("limitations", "")
                approach = request.POST.get("approach", "")
                benefits = request.POST.get("benefits", "")
                opportunities = request.POST.get("opportunities", "")
                nobel = request.POST.get("nobel", "")
                threat = request.POST.get("threat", "")
                financial = request.POST.get("financial", "")
                risk = request.POST.get("risk", "")
                print(logo)
                
                form = Formi(pro_date=pro_date,name=name,role=role,logo=logo,summary=summary,project=project,
                limitations=limitations,approach=approach,benefits=benefits,opportunities=opportunities,
                nobel=nobel,threat=threat,financial=financial,risk=risk)

            messages.success(request, f'Template was created successfully')
            form.save()
            return redirect('btamplate:createTemplate')
    else:
        form = createForm()
    return render(request, 'btamplate/createTemplate.html', {'form': form})

def index(request):
    return render(request, "btamplate/base.html", {})

def contact(request):
    if request.method == "POST":
	    message_name = request.POST['message-name']
	    message_email = request.POST['message-email']
	    message = request.POST['message']
		# send an email
	    send_mail(
		    message_name, # subject
		    message, # message
		    message_email, # from email
		['devtespace@gmail.com'], # To Email
			)

	    return render(request, 'btamplate/contact.html', {'message_name': message_name})

    else:
        return render(request, "btamplate/contact.html", {})

def update(request):
    user_form = Formi.objects.all()
    return render(request, "btamplate/update.html",{'user_form':user_form})


def delete_template(request, object_id):
    user_form = Formi.objects.get(pk = object_id)
    if request.method == 'POST':
        user_form.delete()
        return redirect('btamplate:update')
    return render(request, 'btamplate/delete_template.html')

def update_template(request, object_id):
    user_form = Formi.objects.get(pk = object_id)
    form = updateTemplate(instance=user_form)
    if request.method == 'POST':
        form = updateTemplate(request.POST, instance=user_form)
        if form.is_valid():
            form.save()
        return redirect('btamplate:update')
    context = {
         
         'form':form
     }   
    return render(request, 'btamplate/createTemplate.html', context)

class CustomerListView(ListView):
    model = Formi
    template_name = 'btamplate/update.html'

def render_pdf_view(request, object_id):
    user_form = Formi.objects.get(pk = object_id)
    template_path = 'btamplate/image.html'
    context = {'user_form':user_form}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename="Business_Case.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

def email(request, object_id):
    if request.method == "POST":
        user_form = Formi.objects.get(pk = object_id)
        to = request.POST.get('toemail')
        content = request.POST.get('content')
        html_content = render_to_string("btamplate/email_template.html",{'title':'test email','content':content,'user_form':user_form})
        text_content = strip_tags(html_content)
        email = EmailMultiAlternatives(
            "Business Case",
            content,
            settings.EMAIL_HOST_USER,
            [to]
        )
        email.attach('Business_Case.pdf', html_content)
        email.send()
        return render(
            request,
            'btamplate/email.html',
            {
                'title':'send an email'
            }
        )
    else:
        return render(
            request,
            'btamplate/email.html',
            {
                'title':'send an email'
            }
        )

btamplate/templates/btamplate/base.html
{% load static %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<title>{% block title %}Business Case {% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
    <a href="/btamplate/" class="navbar-brand">
        <h1 class="m-0 text-primary"><img height="10px" src="{% static 'images/logo.png' %}" alt="" class="navbar-brand"/></h1>
    </a>
    <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav mx-auto">
            <a href="/btamplate/" class="nav-item nav-link active"> Home</a>
            <a href="#about_section" class="nav-item nav-link"> About Us</a>
            <a href="/btamplate/contact/" class="nav-item nav-link"> Contact Us</a>
            </div>
        </div>
        <a href="/btamplate/signup/" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Register<i class="fa fa-arrow-right ms-3"></i></a>
    </div>
</nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12">
    {% block body %}
    <div class="banner text-center" data-scroll-index='0'>
        <div class="banner-overlay">
          <div class="container">
            <h1 class="text-capitalize">Best Template for Business Case</h1>
            <p>We help SMEs to create business cases.</p>
            <a href="#about_section" class="btn-btn-outline-success">Learn More</a> </div>
        </div>
      </div>
	  <section id="about_section">
      <div class="about-us section-padding" data-scroll-index='1'>
        <div class="cont">
          <div class="row">
            <div class="col-md-12 section-title text-center">
             <hr>
              <span class="section-title-line"></span> </div>
            <div class="col-md-6 mb-50">
              <div class="section-info">
                <div class="sub-title-paragraph">
                  <h4>Motivation of this App.</h4>
                  <p>This project was motivated by noticing that most SMEs are struggling and they do not have a proper structure or templates of some sort to follow. Some businesses do create good business cases but half way through the project they fail to stick to it due to changes that happen as the project is progressing. Some stop going back to the business case as soon as they start gaining the benefits even though the project is not fully complete and that leads to the project not being a success at the end of the day.</p>
                </div>
                 </div>
            </div>
            <div class="col-md-6 mb-50">
              <div class="section-imge"> <img height="100px" src="{% static 'images/business_case.png' %}" alt="" class="img-responsive"/> </div>
            </div>
          </div>
        </div>
      </div>
	  </section>
      <div class="services section-padding bg-grey" data-scroll-index='2'>
        <div class="container">
          <div class="row">
            <div class="col-md-12 section-title text-center">
              <h3>Our Company</h3>
              <p>We provide you with the best digital business case template.</p>
              <span class="section-title-line"></span> </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-30">
              <div class="service-box bg-white text-center">
                <div class="icon"> <i class="fas fa-chart-line"></i> </div>
                <div class="icon-text">
                  <h4 class="title-box">Objectives</h4>
                  <p>We want SMEs to have a clear, ongoing basis for determining whether the project is worth continuing or not.
					<div>Introduce a digital scape that SMEs will have a common understanding of the value the project is intended to produce.</div>
					<div>To commission digital business case for SMEs to replicate for their business needs.</div>
				</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-30">
              <div class="service-box bg-white text-center">
                <div class="icon"> <i class="fas fa-bullhorn "></i> </div>
                <div class="icon-text">
                  <h4 class="title-box">Mission</h4>
                  <p>Our mission is to help SME with developing digital business case template for any kind of projects they would like to pursue.
					The Business case will help them to determine the feasibility of their projects.</p>
                </div>
              </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 mb-30">
              <div class="service-box bg-white text-center">
                <div class="icon"> <i class="fas fa-map-marked"></i> </div>
                <div class="icon-text">
                  <h4 class="title-box">Vision</h4>
                  <p>Our vision is to be the number one app that provides businesses or coompanies with the best digital business case templates.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>   
  </div>
  </div>
  </div>
  <footer class="footer-copy">
    <div class="container-fluid">
       <div class="row">
   <div class="col-md-12">
   <p> &copy; 2022 All rights reserved. @Solutions</a></p>
    </div>
</div>
    </div>
    </footer>
  {% endblock %}
</body>
</html>

btamplate/templates/btamplate/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <title>{% block title %}Business Case {% endblock %}</title>
</head>
<nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
  <a href="/btamplate/" class="navbar-brand">
      <h1 class="m-0 text-primary"><img height="10px" src="{% static 'images/logo.png' %}" alt="" class="navbar-brand"/></h1>
  </a>
  <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
      <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
      <div class="navbar-nav mx-auto">
          <a href="/btamplate/" class="nav-item nav-link active"> Home</a>
          <a href="/btamplate/" class="nav-item nav-link"> About Us</a>
          <a href="/btamplate/contact/" class="nav-item nav-link"> Contact Us</a>
          </div>
      </div>
      <a href="/btamplate/signup/" class="btn btn-primary rounded-pill px-3 d-none d-lg-block">Register<i class="fa fa-arrow-right ms-3"></i></a>
  </div>
</nav>

<body>
<div class="message bg-white">
  {% if message_name %}
    <center>
      <h2>Thanks {{ message_name }}!</h2>
      <p>We received your email and will respond shortly...</p>
    </center>
    <br/><br/><br/>
  {% else %}
  {% endif %}
  </div>
{%block body%}
  <section class="contact-area">

        <div class="col-12 col-md-0">
          <div class="contact-form">
            <div class="section-heading">
              <h2>Contact Us For More Information</h2>
              <div class="line"></div>
            </div>
            <form action="" method="post">
              {% csrf_token %}
              <div class="row">
                <div class="col-lg-6">
                  <input type="text" name="message-name" class="form-control mb-5" placeholder="Your Name">
                </div>
                <div class="col-lg-6">
                  <input type="email" name="message-email" class="form-control mb-5" placeholder="Your Email">
                </div>
                <div class="col-12">
                  <textarea name="message" class="form-control mb-5" placeholder="Your Message"></textarea>
                </div>
                <div class="col-12">
                  <button type="submit" class="btn dento-btn">Send Message</button>
                </div>
              </div>
            </form>

          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}
</section>
<footer class="footer-copy">
  <div class="container-fluid">
     <div class="row">
 <div class="col-md-12">
 <p> &copy; 2022 All rights reserved. @Solutions</a></p>
  </div>
</div>
  </div>
  </footer>

</body>
</html>

btamplate/templates/btamplate/delete_template.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><i class="fa-solid fa-calendar-lines-pen"></i></title>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static '/css/main.css' %}">
</head>
<body>
    <div class="header">
</div>
    <div class="containerr">
    <form method="POST" action="">
        {% csrf_token %}
        <h4>Are you sure you want to delete?</h4><br>
        <input  class="btn btn-danger" type="submit" value="Yes"/>
    
        <a href="/btamplate/update/"><div class="btn btn-primary">Cancel</div></a>
    </form>
    </div>
  </section>
  <footer class="footer">
    <div class="container-fluid">
       <div class="row">
   <div class="col-md-12">
   <p> &copy; 2022 All rights reserved. @Solutions</a></p>
    </div>
</div>
    </div>
    </footer>
</body>
</html>

btamplate/templates/btamplate/email.html
{% load static %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <title>{% block title %}Business Case {% endblock %}</title>
</head>
<body>
    <body>
        <div class="header">
            <a href="/btamplate/" class="nav-item nav-link active"> {% bs_icon 'arrow-left-short' color='black' size='1em'  %} Back</a>
    </div>
    <div class="email">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
    <section class="row">
        <table>
            <tr>
                <td class="schedule-offset" colspan="2">TO:</td>
                <td><input type="email" name="toemail" required></td>

            </tr>
            <tr>
                <td class="schedule-offset" colspan="2">Message:</td>
                 <td><textarea name="content" readonly id="" cols="40" rows="10" required>@Solutions Busines Case Template</textarea></td>
            </tr>
            <tr>
                <td>
                    <input type="submit" value="Submit" class="btn btn-outline-success rounded-pill>
                </td>
            </tr>
        </table>
    </form>
</div>
</section>
<footer class="footer-copy">
  <div class="container-fluid">
     <div class="row">
 <div class="col-md-12">
 <!-- <p> &copy; 2022 All rights reserved. @Solutions</a></p> -->
  </div>
</div>
  </div>
  </footer>
</body>
</html>

btamplate/templates/btamplate/update.html
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static '/css/main.css' %}">
  <title>{% block title %}Business Case{% endblock %}</title>
  <style>
    .container {
  margin: auto;
  background: #fff;
    width: 50%;
    border: 1px solid #90CAF9;
    padding: 10px;
    border-radius: 10px;
}
.header {
  background: #fff;
  margin-bottom: 100px;
  padding: 30px;
  width: 100%;
  overflow: auto;
}
table {
  margin-bottom: 20px;
  width: 100%;
}
table:last-child {
  margin-bottom: 0px;
}
th,
td {
  padding-bottom: 6px;
  vertical-align: top;
}
th {
  padding-right: 45px;
  text-align: right;
  width: 20%;
}
td {
  width: 40%;
}
thead {
  line-height: 44px;
}
thead th {
  color: #648880;
  font-size: 24px;
}
tbody th {
  color: #a9b2b9;
  font-size: 14px;
  font-weight: 400;
  padding-top: 22px;
  text-transform: uppercase;
}
tbody td {
  border-top: 1px solid #dfe2e5;
  padding-top: 21px;
}
tbody td:first-of-type {
  padding-right: 15px;
}
tbody td:last-of-type {
  padding-left: 15px;
}
tbody td:only-of-type {
  padding-left: 0;
  padding-right: 0;
}
table a {
  color: #888;
}
table h4 {
  margin-bottom: 0;
}
.schedule-offset {
  color: #000;
}
section{
  margin: 20px;
}
.footer-copy {
  background: #fafafa;
  color: #000;
  font-size: 13px;
  text-align: center;
  padding:30px;
  margin-top: 100px;
  overflow: auto;
  bottom: 0px;
  position: relative;
  height: 50px;
  left: 0px;
  right: 0px;
  }
  
  </style>
  </head>
<body>
  <body>
    <div class="header">
        
      </div>
    <section class="row">
      <div class="container">
        <table>
		{% for user_form in user_form %}
          <thead>
            <tr>
              <th scope="row">
              </th>
              <td>
					Date:{{user_form.pro_date}}<br>
					Submitted by:{{user_form.name}}<br>
					Role/Title:{{user_form.role}}<br>
              </td>
			   <td>
                  <h4> {% if user_form.logo %}
				<img src="{{ user_form.logo.url }}" alt="image" width="150px">
					{% endif %}</h4>
              </td>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row">
				Exective Summary:
              </th>
              <td class="schedule-offset" colspan="2">
               {{user_form.summary}}
              </td>
            </tr>
            <tr>
              <th scope="row">
			  Project:
              </th>
              <td class="schedule-offset" colspan="2">
              {{user_form.project}}
              </td>
            </tr>
            <tr>
              <th scope="row">
               Limitations:
              </th>
              <td class="schedule-offset" colspan="2">
               {{user_form.limitations}}
              </td>
            </tr>
            <tr>
              <th scope="row">
                Approach:
              </th>
              <td class="schedule-offset" colspan="2">
                {{user_form.approach}}
              </td>
            </tr>
			  <tr>
              <th scope="row">
                Benefits:
              </th>
              <td class="schedule-offset" colspan="2">
                {{user_form.benefits}}
              </td>
            </tr>
			  <tr>
              <th scope="row">
                Opportunities:
              </th>
              <td class="schedule-offset" colspan="2">
               {{user_form.opportunities}}
              </td>
            </tr>
			  <tr>
              <th scope="row">
                Nobel:
              </th>
              <td class="schedule-offset" colspan="2">
                {{user_form.nobel}}
              </td> 
            </tr>
			  <tr>
              <th scope="row">
                Threat:
              </th>
              <td class="schedule-offset" colspan="2">
                {{user_form.threat}}
              </td>
            </tr>
			  <tr>
              <th scope="row">
                Financial:
              </th>
              <td class="schedule-offset" colspan="2">
                {{user_form.financial}}
              </td>
            </tr>
			  <tr>
              <th scope="row">
                Risk:
              </th>
              <td class="schedule-offset" colspan="2">
              {{user_form.risk}}
              </td>
            </tr>
				  <tr>
              <th scope="row">
                <a href="{% url 'btamplate:test-view' user_form.pk %}">{% bs_icon 'file-earmark-pdf' color='green' size='1.5em'  %} Pdf</a>
              </th>
              <td>
                <a href="{% url 'btamplate:delete_template' user_form.pk %}">{% bs_icon 'trash3-fill' color='red' size='1.5em'  %}Delete</a>
              </td>
			   <td>
          <a href="{% url 'btamplate:email' user_form.pk %}">{% bs_icon 'envelope-fill' color='grey' size='1.5em'  %}Email</a>
              </td>
			       <td>
           
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
     </div>
    </section>

    <footer class="footer-copy">
      <div class="container-fluid">
         <div class="row">
     <div class="col-md-12">
     <p> &copy; 2022 All rights reserved. @Solutions</a></p>
      </div>
  </div>
      </div>
      </footer>
</body>
</html>